# Generated by Django 4.2 on 2026-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
