# Generated by Django 4.2 on 2026-06-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_img',
            field=models.ImageField(blank=True, null=True, upload_to='department_hod/'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
