# Generated by Django 4.2 on 2026-06-03 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department_designation_department_hod_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('vidhan_sabha', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=300)),
                ('village_name', models.CharField(max_length=300)),
                ('head_name', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('scheme_type', models.CharField(max_length=200)),
                ('work_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.division')),
            ],
        ),
    ]
