# Generated by Django 4.2 on 2026-06-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.department'),
        ),
    ]
