# Generated by Django 4.2 on 2026-06-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_work_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='work_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_outlay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dm_level_funds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_as_on_date', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('surrendered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('physical_target', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.work')),
            ],
        ),
    ]
