# Generated by Django 4.2 on 2026-06-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_workimage_workdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.work', to_field='work_id'),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.work', to_field='work_id'),
        ),
    ]
